### ISSUE TITLE
Add script to `release` action which creates submodules tags

### ISSUE THREAD

**Issue by kozmod** [kozmod/oniontx#120]
### Description
Need to add submodules tags automatically. Try to use `actions/github-script@v7`:
```yaml
      - name: Set submodule tags
        uses: actions/github-script@v7
        with:
          script: |
            const creator = github.ref_name
            let submodules: string[] = ['stdlib', 'pgx', 'sqlx', 'gorm'];
            
            for (const submodule of submodules) {
              echo 'refs/tags/${{ ref_name }}'
            }
```
