### ISSUE TITLE
Remove unnecessary workflow steps

### ISSUE THREAD

**Issue by kozmod** [kozmod/oniontx#121]
### Description
Need to remove
```yml
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.0

      - name: Run migrations // remove
        run: |
          go version

      - name: Run migrations
        run: |
          cd test/integration/migration
          go run . -cmd up -url "postgresql://test:passwd@localhost:5432/test?sslmode=disable"
      
```
